# This is a basic workflow to help you get started with Actions

name: "Build kernels"

workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependency
        run: |
