name: "Build kernels"

on:
  workflow_dispatch:
    inputs:
      banner:
          description: 'link preview banner'
          required: true
      changelog:
          description: 'changelog your kernel'
          required: true
          default: 'https://github.com/MI8953-Project/android_kernel_xiaomi_ysl/commits/dts/audio/'
      devicename:
          description: 'Codename Device'
          required: true
          default: 'MI8953'
      defconfig:
          description: 'defconfig target'
          required: true
      download:
          description: 'download link like "github release, sf"'
          required: true
          default: 'https://t.me/altsanymouse'
      kernelname:
          description: 'Kernel name'
          required: true
          default: 'Alts-Kernel'
      repo:
          description: 'Kernel source link'
          required: true
          default: 'https://github.com/MI8953-Project/android_kernel_xiaomi_ysl'
      branch:
          description: 'Kernel source branch'
          required: true
          default: 'dts/audio'
      clangrepo:
          description: 'Clang source link'
          required: true
          default: 'https://github.com/kdrag0n/proton-clang'
      clangbranch:
          description: 'Clang source branch'
          required: true
          default: 'master'
      

env:
  TZ: Asia/Jakarta
  PHOTO: ${{ github.event.inputs.banner }}
  CHANGELOG: ${{ github.event.inputs.changelog }}
  DEFCONFIG: ${{ github.event.inputs.defconfig }}
  DEVICENAME: ${{ github.event.inputs.devicename }}
  DOWNLOAD: ${{ github.event.inputs.download }}
  KERNELNAME: ${{ github.event.inputs.kernelname }}
  REPO: ${{ github.event.inputs.repo }}
  BRANCH: ${{ github.event.inputs.branch }}
  CLANGREPO: ${{ github.event.inputs.clangrepo }}
  CLANGBRANCH: ${{ github.event.inputs.clangbranch }}
          

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Environment 
        run: |
          git config --global user.name "$GIT_USERNAME"
          git config --global user.email "$GIT_USER_EMAIL"
          wget https://raw.githubusercontent.com/shenprjkt/Alts-KernelCI/main/Common/Dependency.sh
          bash Dependency.sh

        env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}

      - name: Build Kernel
        run: |
          wget https://raw.githubusercontent.com/shenprjkt/Alts-KernelCI/main/Common/Build.sh
          bash Build.sh

      - name: Zipping Kernel 
        run: |
          wget https://raw.githubusercontent.com/shenprjkt/Alts-KernelCI/main/Common/Zipping.sh
          bash Zipping.sh

      - name: Upload Telegram 
        run: |
          wget https://raw.githubusercontent.com/shenprjkt/Alts-KernelCI/main/Common/post.sh
          bash post.sh

        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}

      - name: Post Update
        run: |
          wget https://raw.githubusercontent.com/shenprjkt/Alts-KernelCI/main/Common/Upload.sh
          bash Upload.sh

        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}

          
          
