name: "Build kernels"

on:
  workflow_dispatch:
    inputs:
      defconfig:
          description: 'defconfig target'
          required: true
      kernelname:
          description: 'Kernel name'
          required: true
          default: 'Alts-Kernel'
      user:
          description: 'Build User Name'
          required: true
          default: 'https://github.com/MI8953-Project/android_kernel_xiaomi_ysl'
      host:
          description: 'Build Host Name'
          required: true
          default: 'dts/audio'
      repo:
          description: 'Kernel source link'
          required: true
          default: 'https://github.com/MI8953-Project/android_kernel_xiaomi_ysl'
      branch:
          description: 'Kernel source branch'
          required: true
          default: 'dts/audio'
      clangname:
          description: 'Clang name'
          required: true
          default: 'proton-clang'
      clangrepo:
          description: 'Clang source link'
          required: true
          default: 'https://github.com/kdrag0n/proton-clang'
      clangbranch:
          description: 'Clang source branch'
          required: true
          default: 'master'

env:
  TZ: Asia/Jakarta
  DEFCONFIG: ${{ github.event.inputs.defconfig }}
  KERNELNAME: ${{ github.event.inputs.kernelname }}
  REPO: ${{ github.event.inputs.repo }}
  BRANCH: ${{ github.event.inputs.branch }}
  CLANGNAME: ${{ github.event.inputs.clangname }}
  CLANGREPO: ${{ github.event.inputs.clangrepo }}
  CLANGBRANCH: ${{ github.event.inputs.clangbranch }}
  USER: ${{ github.event.inputs.user }}
  HOST: ${{ github.event.inputs.host }}
          

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Environment 
        run: |
          git config --global user.name "$GIT_USERNAME"
          git config --global user.email "$GIT_USER_EMAIL"
          wget https://raw.githubusercontent.com/shenprjkt/Alts-KernelCI/main/Common/Dependency.sh
          bash Dependency.sh

        env:
          GIT_USERNAME: ${{ secrets.GIT_USERNANE }}
          GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}

      - name: Build Kernel
        run: |
          wget https://raw.githubusercontent.com/shenprjkt/Alts-KernelCI/main/Common/Build.sh
          bash Build.sh
          
